### ISSUE TITLE
do you know of any way to reverse it? (hex value to NCS)

### ISSUE THREAD

**Issue by ssuess** [m90/ncs-color#1]
Hi, and thanks for this script it is great...is it possible to go in the other direction, taking a hex value and converting it to NCS?

**Comment by m90** [comment]
Unfortunately I guess the other was around won't be that easy, due to the fact that 8 bit RGB colorspace is far bigger than the 1950 NCS colors: https://www.quora.com/What-is-a-way-to-easily-convert-from-RGB-red-green-blue-to-NCS-natural-color-system

If you really need to pull this off I guess you will need a map of all NCS colors and their RGB approximations, enabling you to find the closest RGB sibling of your input and then simply do the to NCS conversion by lookup.

**Comment by milahu** [comment]
here is a start : )

https://github.com/milahu/ncs-analyzer

the orange curve shows the piecewise linear interpolation curve

the black scatterplot shows the difference between the ncs hue and the hsl/hsv hue
= between four color wheel and three color wheel

the goal is to linearize (and prettify) this difference curve, so that

* we get a smooth curve
* we get a fast ncs2rgb function
* we can easily get a rgb2ncs function

smooth curve:
also around the four primary colors, where the current algorithm is not defined
so we have no data for `phi < 10 || 90 < phi`
around blue, the current algorithm produces a small spike

the project can be generalized to a graphical function editor
where we can manually generate linear functions from arbitrary data

**Comment by ElPeineta** [comment]
> Hi, and thanks for this script it is great...is it possible to go in the other direction, taking a hex value and converting it to NCS?

Can I ask why you want to go in the other direction?:)

**Comment by forthrin** [comment]
Me three. Use case for going reverse is, you have played with HSL sliders on your living room wall, and you want to find which NCS codes this corresponds to. Saying codes, because screen to real life is imprecise, so you need a range.

**Comment by milahu** [comment]
> living room wall

to measure hardware colors, you can use a color fan deck
see [NCS color fan deck](https://ncscolour.com/en-eu/collections/design-tools) or [NCS color reader](https://ncscolour.com/en-eu/collections/digital-colour-tools)

or, you know, brute force it by playing with [NCS sliders](https://github.com/milahu/alchi/blob/12a3992f45c3f6c49c781387d18d9bff07d0b0e3/src/alchi-test/src/App.svelte#L868)
until you get similar HSL values

**Comment by forthrin** [comment]
Post here if you add a reverse lookup or come across a software that does.
